# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "#icodeformyभाषा"
title_custom: "<span style='font-family: monospace;'>#icodeformy<span style='color:#1d5965;'>भाषा</span></span>"
description:	       "Nepali and Low-Resource NLP"
author:              "Shreeya Dhakal"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
