# Change 'comments' to true for Disqus comments
disqus:
  comments: 'comments'
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Nepali Grammar',      url: 'nepali-grammar'}
- {name: 'Low-Resource NLP',       url: 'low-resource-nlp'}
- {name: 'NLP Fundamentals',       url: 'nlp-fundamentals'}
- {name: 'Resources',       url: 'resources'}
- {name: 'About',              url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:  'https://www.linkedin.com/in/shreeyya/'}
- {icon: 'instagram', link:  'https://instagram.com/shreeyadl'}
- {icon: 'envelope', link:   'mailto:shreeyadhakal05@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
